import { Link, createFileRoute } from "@tanstack/react-router";
import microbesImage from "@/assets/evergreen-microbes.jpg";
import fertilizerImage from "@/assets/evergreen-fertilizer.jpg";
import compostImage from "@/assets/evergreen-compost.jpg";
import cocopeatImage from "@/assets/evergreen-cocopeat.jpg";
import { PageIntro, SectionLabel } from "@/components/storefront";

export const Route = createFileRoute("/categories")({ head: () => ({ meta: [{ title: "Categories — Evergreen Media" }, { name: "description", content: "Find the right soil, root and plant nutrition category for your growing practice." }, { property: "og:title", content: "Categories — Evergreen Media" }, { property: "og:description", content: "Find the right soil, root and plant nutrition category for your growing practice." }] }), component: CategoriesPage });
const categories = [["Biofertilizers", "Live cultures for living soil", microbesImage], ["Organic Fertilizers", "Slow-release natural nutrition", fertilizerImage], ["Soil Enhancers", "Build a richer soil profile", compostImage], ["Growing Media", "Cocopeat and root substrates", cocopeatImage], ["Plant Nutrition", "Thoughtful inputs for growth", fertilizerImage], ["Plant Protection", "Botanical everyday care", compostImage]];
function CategoriesPage() { return <main className="mx-auto max-w-[1440px] px-6 pb-24 lg:px-10"><PageIntro eyebrow="Find your foundation" title={<>Choose by <span className="italic text-gold">need.</span></>} description="Every category begins with the same question: what would help this growing environment feel more supported?" /><div className="grid grid-cols-1 gap-x-8 gap-y-12 py-16 sm:grid-cols-2 lg:grid-cols-3">{categories.map(([name, description, image], index) => <Link to="/shop" key={name} className="group"><img src={image} alt={`${name} collection`} loading="lazy" width={1024} height={1024} className={`w-full rounded-[min(1vw,12px)] object-cover transition duration-700 group-hover:scale-[1.02] ${index === 1 || index === 4 ? "aspect-[4/5]" : "aspect-square"}`} /><div className="mt-4 flex items-end justify-between border-b border-ink/10 pb-4"><div><SectionLabel index={`0${index + 1}`}>{name}</SectionLabel><h2 className="mt-2 font-display text-3xl text-forest-deep">{name}</h2><p className="mt-1 text-xs text-ink/60">{description}</p></div><span className="text-2xl text-gold">↗</span></div></Link>)}</div></main>; }